use tablepro_core::{ColumnInfo, QueryResult, TableInfo, Value};
use tablepro_storage::{ConnectionOrganization, ConnectionOrganizationIndex, SavedConnection};
use uuid::Uuid;

use super::OpenMode;

#[derive(Debug)]
pub enum AppMsg {
    OpenConnect,
    ConnectionPrepared(Box<crate::services::connection_service::PreparedConnection>),
    ConnectionPrepareFailed(String),
    ConnectionSwitchDecision(super::types::SwitchDecision),
    DialogClosed,
    SelectTable {
        schema: Option<String>,
        name: String,
        open_mode: OpenMode,
    },
    ColumnsLoaded(Uuid, Vec<ColumnInfo>, u64),
    RowsLoaded(Uuid, u64, QueryResult, u64),
    LoadFailed(Option<Uuid>, String, Option<u64>),
    RowOpStarted,
    ReloadConnections,
    ConnectionsLoaded(Vec<SavedConnection>),
    OpenSaved(SavedConnection),
    DeleteConnection(Uuid),
    ConnectionOrganizationLoaded(ConnectionOrganizationIndex),
    ToggleConnectionFavorite(Uuid),
    OrganizeConnection(SavedConnection),
    SetConnectionOrganization(Uuid, ConnectionOrganization),
    ConnectionOrganizationRejected,
    ImportConnectionUrl,
    ImportConnectionUrlText(String),
    ImportConnectionUrlSucceeded(String),
    ImportConnectionUrlFailed,
    NewEditorTab,
    CloseActiveWorkspaceTab,
    EditorTabRunStateChanged(Uuid, bool),
    EditorTabQueryChanged(Uuid, String),
    EditorNeedsColumns(Vec<String>),
    FavoritesLoaded(Vec<tablepro_storage::SavedQuery>),
    PersistFavorite(tablepro_storage::SavedQuery),
    FavoriteSaved,
    FavoriteSaveFailed(String),
    SaveQueryAsFavorite,
    ShowQuickSwitcher,
    QuickSwitcherChose(crate::services::quick_switcher::QuickTarget),
    SchemaColumnsFetched(String, Vec<String>),
    ShowHistory,
    OpenHistoryQuery(String),
    ReplaceActiveTabQuery(String),
    Disconnect,
    ForceDisconnect,
    PollHealth,
    RefreshPage,
    ShowShortcuts,
    ShowAbout,
    ShowActivity,
    ExplainActiveQuery,
    ShowPreferences,
    NewWindow,
    RowCountLoaded(Uuid, u64, u64),
    ExportCsv,
    ExportJson,
    CopyToClipboard(String),
    CopyRowAsInsert {
        tab_id: Uuid,
        row_position: u32,
    },
    FetchBrowsePage(Uuid),
    FetchBrowseColumns(Uuid),
    FetchBrowseRowCount(Uuid),
    WorkspaceSchemaWordsChanged,
    WorkspaceTabClosed(Uuid),
    CloseOtherWorkspaceTabs(Uuid),
    CloseWorkspaceTabsToRight(Uuid),
    WorkspaceTabsChanged,
    ExecuteBrowseTransaction {
        tab_id: Uuid,
        statements: Vec<(String, Vec<Value>)>,
        sources: Vec<crate::services::change_tracker::StatementSource>,
    },
    SaveCompletedForTab(Uuid, Option<String>),
    SaveFailedForTab(Uuid, String),
    FlashErrorRowForTab(Uuid, crate::services::change_tracker::StatementSource),
    SaveActiveBrowseTab,
    SaveActiveBrowseTabById(Uuid),
    UndoActiveBrowseTab,
    RedoActiveBrowseTab,
    ShowAlert {
        title: String,
        body: String,
    },
    ShowToast(String),
    BrowseTabDirtyChanged(Uuid, bool),
    NewTableTab {
        schema: Option<String>,
    },
    EditStructureTab {
        schema: Option<String>,
        table: String,
    },
    ShowCreateTableForExisting {
        schema: Option<String>,
        table: String,
    },
    ShowCreateTableLoaded {
        sql: String,
    },
    DropTablePrompt {
        schema: Option<String>,
        table: String,
    },
    DropTableConfirmed {
        schema: Option<String>,
        table: String,
    },
    DropTableSucceeded {
        schema: Option<String>,
        table: String,
    },
    ExecuteStructureTransaction {
        tab_id: Uuid,
        statements: Vec<String>,
    },
    SaveActiveStructureTabById(Uuid),
    StructureSaveCompleted {
        tab_id: Uuid,
        new_table_name: Option<String>,
    },
    StructureSaveFailed(Uuid, String),
    FetchStructureData {
        tab_id: Uuid,
    },
    StructureDataLoaded {
        tab_id: Uuid,
        columns: Vec<ColumnInfo>,
        indexes: Vec<tablepro_core::IndexInfo>,
        fks: Vec<tablepro_core::ForeignKeyInfo>,
    },
    StructureLoadFailed {
        tab_id: Uuid,
        message: String,
    },
    StructureTabDirtyChanged(Uuid, bool),
    SchemaChanged {
        schema: Option<String>,
        table: Option<String>,
    },
    TablesReloaded(Vec<TableInfo>),
    ReopenClosedTab,
    ShowFilterDialog,
}
