mod activity_dialog;
mod app;
mod browse_tab;
mod cell_editor;
mod connect_dialog;
mod connection_row;
mod editor;
pub(crate) mod error_text;
mod explain_dialog;
mod filter_strip;
mod grid;
mod history_dialog;
mod mcp_preferences;
mod parameters_dialog;
mod preferences;
mod quick_switcher_dialog;
mod row_object;
mod sidebar_row;
mod ssh_section;
mod structure_tab;
mod structure_tab_dialogs;
mod welcome_view;

pub use app::App;
