#!/usr/bin/env python3
"""Print the ignored-test ledger from Rust declarations; no files are modified."""
from pathlib import Path
import re
from collections import Counter

root = Path(__file__).resolve().parents[1]
rows = []
for path in sorted((root / "crates").rglob("*.rs")):
    source = path.read_text()
    for match in re.finditer(r'#\[ignore(?:\s*=\s*"([^"\n]*)")?\]', source):
        function = re.search(r'\b(?:async\s+)?fn\s+(\w+)', source[match.end():])
        if not function:
            raise RuntimeError(f"ignore without function: {path}")
        name = function.group(1)
        reason = match.group(1) or "subprocess helper; invoked by its parent test"
        relative = path.relative_to(root).as_posix()
        if "subprocess" in name or not match.group(1):
            tier, enable = "Helper", "Run parent unit/sandbox test; do not enable globally"
        elif "driver-tls-tests" in relative:
            tier, enable = "TLS", "scripts/test-driver-tls.sh"
        elif "release-tests" in relative:
            tier, enable = "Release", "scripts/test-postgres-release.sh"
        elif "socket" in relative:
            tier, enable = "Socket", "scripts/test-postgres-socket.sh"
        elif "smoke_local" in relative:
            tier, enable = "Smoke", "scripts/smoke-postgres.sh against disposable DB"
        elif "Secret Service" in reason or "secret" in relative:
            tier, enable = "Keyring", "scripts/test-secret-service.sh in isolated session"
        elif "docker" in reason.lower():
            engine = path.relative_to(root).parts[2]
            tier, enable = "Driver", f"Docker plus cargo test -p tablepro-driver-{engine} --test integration -- --include-ignored --test-threads=1"
        else:
            tier, enable = "Fixture", reason
        rows.append((relative, name, tier, reason, enable))
print("# Ignored-test inventory\n")
print("Generated by `python3 scripts/inventory-ignored-tests.py` from the working tree.\n")
print("These attributes select an execution environment; helper attributes are not missing coverage. Keep fixture tests ignored in the ordinary unit tier. Enable them through their runner once its prerequisites exist.\n")
print(f"Total: {len(rows)} declarations. " + "; ".join(f"{k}: {v}" for k, v in sorted(Counter(r[2] for r in rows).items())) + ".\n")
print("| Test | Tier | Reason | Activation condition / runner |\n|---|---|---|---|")
for path, name, tier, reason, enable in rows:
    print(f"| [{name}](../{path}) | {tier} | {reason} | `{enable}` |")
